gems:
  - jekyll/scholar
  - jekyll-last-modified-at

timezone: Europe/Paris

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Alexis Duque'

tagline:          'PhD student at the CITI Lab, INSA Lyon - Agora Team, INRIA.'
description:      'PhD student, CITI Lab.<br>Embedded Soft. Engineer, Rtone.'
url:              http://perso.citi-lab.fr/aduque
baseurl:          ''
update: 'October 16, 2016'

author:
  name: 'Alexis Duque'
  email: 'alexis.duque[at]mail[dot]insa-lyon[dot]fr'
  github: alexisduque
  twitter: alexis0duque
  linkedin: alexisduque
  google_scholar: https://scholar.google.fr/citations?user=P9BIZW0AAAAJ
  email_md5: 83124b745752d1a1b0ca2eee1af0bd48
  disqus_shortname: alexisduque
  bio: PhD student at the CITI Lab of INSA de Lyon, Urbanet Team - Embedded Software Engineer at Rtone.
  google_analytics_id: 'UA-73113604-1'
  google_analytics_url: 'auto'
# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/alexisduque/alexisduque.github.io

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
